spring:
  application:
    name: demo
  profiles:
    active: local

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
  shutdown: graceful

logging:
  config: classpath:log-config.xml
  level:
    root: info
    com.example.demo.aop: debug # ?? ????? ?? ??
